### ISSUE TITLE
Incompatible with ember donation systems ( And some other addons with same problem )

### ISSUE THREAD

**Issue by mipastu** [Weol/WUMA#41] opened 2020-03-05 23:21 UTC
WUMA is incompatible with ember donation system
( https://www.gmodstore.com/market/view/5620 )

I recently started using ember donation system and its something loadout related with the problem.
WUMA is very highly used in our server and cannot be replaced so something to avoid this would be great fix!

I have noticed this same problem with some other addons, but i have just got rid of them. Now there is not really a choice.

Added weol in steam too about this issue.

```05.03 23:07:26 [Server] - [Ember Syncing the group of MIPλSTU(76561198018477778)
05.03 23:07:26 [Server] INFO L 03/05/2020 - 23:07:26: Lua Error: 
05.03 23:07:26 [Server] INFO [DarkRP] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:792: attempt to index local 'jobTable' (a nil value)
05.03 23:07:26 [Server] INFO 1. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:792
05.03 23:07:26 [Server] INFO 2. GiveLoadout - addons/wuma-master/lua/wuma/loadouts.lua:489
05.03 23:07:26 [Server] INFO 3. RefreshLoadout - addons/wuma-master/lua/wuma/loadouts.lua:496
05.03 23:07:26 [Server] INFO 4. fn - addons/wuma-master/lua/wuma/users.lua:281
05.03 23:07:26 [Server] INFO 5. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
05.03 23:07:26 [Server] INFO 6. SignalUserGroupChanged - gamemodes/darkrp/gamemode/libraries/sh_cami.lua:523
05.03 23:07:26 [Server] INFO 7. applyCAMIgroup - addons/ember/lua/ember/store.lua:5
05.03 23:07:26 [Server] INFO 8. fn - addons/ember/lua/ember/store.lua:58
05.03 23:07:26 [Server] INFO 9. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109
05.03 23:07:26 [Server] INFO [DarkRP] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:792: attempt to index local 'jobTable' (a nil value)
05.03 23:07:26 [Server] INFO 1. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:792
05.03 23:07:26 [Server] INFO 2. GiveLoadout - addons/wuma-master/lua/wuma/loadouts.lua:489
05.03 23:07:26 [Server] INFO 3. RefreshLoadout - addons/wuma-master/lua/wuma/loadouts.lua:496
05.03 23:07:26 [Server] INFO 4. fn - addons/wuma-master/lua/wuma/users.lua:281
05.03 23:07:26 [Server] INFO 5. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
05.03 23:07:26 [Server] INFO 6. SignalUserGroupChanged - gamemodes/darkrp/gamemode/libraries/sh_cami.lua:523
05.03 23:07:26 [Server] INFO 7. applyCAMIgroup - addons/ember/lua/ember/store.lua:5
05.03 23:07:26 [Server] INFO 8. fn - addons/ember/lua/ember/store.lua:58
05.03 23:07:26 [Server] INFO 9. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109
05.03 23:07:26 [Server] INFO L 03/05/2020 - 23:07:26: Lua Error: 
05.03 23:07:26 [Server] INFO [ERROR] addons/smartspawnmanager/lua/autorun/smartspawn/sv_main.lua:362: attempt to index local 'jobTable' (a nil value)
05.03 23:07:26 [Server] INFO 1. PlayerSelectSpawn - addons/smartspawnmanager/lua/autorun/smartspawn/sv_main.lua:362
05.03 23:07:26 [Server] INFO 2. fn - addons/smartspawnmanager/lua/autorun/smartspawn/sv_main.lua:407
05.03 23:07:26 [Server] INFO 3. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109
05.03 23:07:26 [Server] INFO [ERROR] addons/smartspawnmanager/lua/autorun/smartspawn/sv_main.lua:362: attempt to index local 'jobTable' (a nil value)
05.03 23:07:26 [Server] INFO 1. PlayerSelectSpawn - addons/smartspawnmanager/lua/autorun/smartspawn/sv_main.lua:362
05.03 23:07:26 [Server] INFO 2. fn - addons/smartspawnmanager/lua/autorun/smartspawn/sv_main.lua:407
05.03 23:07:26 [Server] INFO 3. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109
05.03 23:07:26 [Server] INFO ServerLog: [FAdmin] MIPλSTU (STEAM_0:0:29106025) Spawned
05.03 23:07:26 [Server] INFO L 03/05/2020 - 23:07:26: [FAdmin] MIPλSTU (STEAM_0:0:29106025) Spawned
05.03 23:07:26 [Server] INFO L 03/05/2020 - 23:07:26: Lua Error: 
05.03 23:07:26 [Server] INFO [DarkRP] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:760: attempt to index local 'jobTable' (a nil value)
05.03 23:07:26 [Server] INFO 1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:760
05.03 23:07:26 [Server] INFO [DarkRP] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:760: attempt to index local 'jobTable' (a nil value)
05.03 23:07:26 [Server] INFO 1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:760
05.03 23:07:26 [Server] INFO L 03/05/2020 - 23:07:26: "MIPλSTU<2><STEAM_0:0:29106025><>" entered the game```

**Comment by Weol** [comment] 2020-03-06 14:33
Since this addon is a paid one, can you link me to any of the other addons that you also experienced this problem with? It will help alot in identifying the cause.

**Comment by Weol** [comment] 2020-03-06 20:58
Added fix 2f18e11f8e57f362b26932e63ab21aab8f2198b6

Waiting for testing before pushing to workshop

**Comment by mipastu** [comment] 2020-03-07 11:47
Issue is gone! Thank you for update.
testing is completed.

**Comment by Weol** [comment] 2020-03-08 16:41
The fix has been pushed to the workshop

**Closed as completed by Weol** 2020-03-08 16:41 UTC
