### ISSUE TITLE
Getting this error when I enter or leave buildmode/ godmode

### ISSUE THREAD

**Issue by Synkstar** [Weol/WUMA#22] opened 2019-03-14 18:56 UTC
[ERROR] addons/wuma-master/lua/wuma/users.lua:242: attempt to index field 'PersonalLoadoutCommand' (a function value)
1. fn - addons/wuma-master/lua/wuma/users.lua:242
2. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109

**Comment by Synkstar** [comment] 2019-03-14 18:56
x86 and x64 gmod

**Comment by Weol** [comment] 2019-03-14 19:52
This was a bug caused by the previous uodate, I have put out an update that fixes this. Thank you alot for telling me about this.

**Comment by Weol** [comment] 2019-03-14 19:53
Fixed by 46947652414517e3f5cfcf8a97104fb4198d30a0

**Closed as completed by Weol** 2019-03-14 19:53 UTC
